food_delivery/config/routes.rb
Rails.application.routes.draw do
 
  # get 'carts/show'
  ActiveAdmin.routes(self)
  devise_for :users
  root 'restaurants#index'

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items/:dish_id' => "line_items#create", as: 'line_items'
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  resources :dishes
  resources :restaurants

end

food_delivery/app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.is_admin?
  end
end

food_delivery/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

food_delivery/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :dishes, through: :line_items
  has_many :restaurants, through: :line_items

  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
  
end

food_delivery/app/models/dish.rb
class Dish < ApplicationRecord
  has_one_attached :picture
  belongs_to :restaurant
  has_many :line_items, dependent: :destroy
  
  validates :name, presence: true,
  length: { minimum: 3, maximum: 20 }


  validates :description, presence: true,
  length: { minimum: 10, maximum: 500 }

  validates :price, presence: true,
  numericality: { greater_than_or_equal_to: 0 }


  validates :picture,  file_content_type: { allow: ['image/jpeg', 'image/gif', 'image/png'] }


end

food_delivery/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :dish
  belongs_to :cart
  belongs_to :user
  belongs_to :restaurant
  
  def total_price
    self.quantity * self.dish.price
  end

end

food_delivery/app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_one_attached :picture
  has_many :dishes, dependent: :destroy
  has_many :line_items, dependent: :destroy

  validates :name, presence: true,
  length: { minimum: 2, maximum: 20 }


  validates :description, presence: true,
  length: { minimum: 10, maximum: 500 }


  validates :picture,  file_content_type: { allow: ['image/jpeg', 'image/gif', 'image/png'] }

end

food_delivery/app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :line_items, dependent: :destroy
         
  validates :name, presence: true, length: { maximum: 50 }

end

food_delivery/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :current_cart

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(:id => session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end

    if session[:cart_id] == nil
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
  end

end

food_delivery/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

food_delivery/app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  
  def index
    @dishes = Dish.all
  end

  
  def show
  end

  
  private
  
  def set_dish
    @dish = Dish.find(params[:id])
  end

  
  def dish_params
    params.require(:dish).permit(:name, :description, :price, :picture, :id)
  end
  
end

food_delivery/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  def create

    chosen_dish = Dish.find(params[:dish_id])
    current_cart = @current_cart


    if current_cart.dishes.include?(chosen_dish)

      @line_item = current_cart.line_items.find_by(:dish_id => chosen_dish)
      @line_item.restaurant = @line_item.dish.restaurant
      @line_item.quantity += 1
    else
      @line_item = LineItem.new
      @line_item.quantity = 1
      @line_item.restaurant = chosen_dish.restaurant
      @line_item.cart = current_cart
      @line_item.dish = chosen_dish
    end

    @line_item.user = current_user
    @line_item.save
    
    redirect_to cart_path(current_cart)
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to cart_path(@current_cart)
  end 

  def add_quantity
    @line_item = LineItem.find(params[:id])
    @line_item.quantity += 1
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    @line_item = LineItem.find(params[:id])
    if @line_item.quantity > 1
      @line_item.quantity -= 1
    end
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  private
  def line_item_params
    params.require(:line_item).permit(:quantity, :dish_id, :cart_id )
  end
end

food_delivery/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  
  def index
    @restaurants = Restaurant.all
  end

  
  def show
  end

  private
  
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :picture)
  end
end

food_delivery/app/helpers/application_helper.rb
module ApplicationHelper
end

food_delivery/app/helpers/carts_helper.rb
module CartsHelper
end

food_delivery/app/helpers/line_items_helper.rb
module LineItemsHelper
end

food_delivery/app/views/carts/show.html.erb
<h1>Cart show</h1>
<ul>
  <% @cart.line_items.each do |line_item| %>
  <li>Item: <%= line_item.dish.name %>/ 
      Price: <%= number_to_currency(line_item.dish.price) %>/ 
      Quantity: <%= line_item.quantity %>/ 
      Total Price: <%= number_to_currency(line_item.total_price) %>
    <ul>
      <li>
        <%= link_to "Add one", line_item_add_path(:id => line_item), method: :post %>
        <%= link_to "Reduce one", line_item_reduce_path(:id => line_item), method: :post %>
      </li>
      <li>
        <%= link_to "Remove item", line_item_path(line_item), method: :delete %>
      </li>
    </ul>
    <% end %>
  </ul>
  
  <h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>

  <%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"}

food_delivery/app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><% if dish.picture.attached? %>
        <%= image_tag dish.picture, size: 100 %>
        <% end %></td>
        <td><%= dish.name %></td>
        <td><%= dish.description %></td>
        <td><%= dish.price %></td>
        <td><%= link_to 'Show', dish %></td>
      </tr>
    <% end %>
  </tbody>
</table>

food_delivery/app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<% if @dish.picture.attached? %>
<%= image_tag @dish.picture, size: 100 %>
<% end %>


<%= link_to 'Back', dishes_path %>

food_delivery/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food Delivery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


   <nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
    <div class="container">
      <h4> </h4>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="navbar-nav ml-auto">
              <div class="navbar-nav ml-auto">
                <% if user_signed_in? %>
            <div class="nav-item">
                <span class="navbar-text">
                  Hello, &nbsp;
                  <span>
                  </div>
                  <div class="dropdown show">
                    <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                  </div>
                  <div>
                  <% else %>
                      <div class="nav-item">
                         <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                      </div>
                      <div class="nav-item">
                         <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                      </div>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</nav>
    <%= yield %>
  </body>
</html>

food_delivery/app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
    <tr>
      <td><% if restaurant.picture.attached? %>
        <%= image_tag restaurant.picture, size: 100 %>
        <% end %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.description %></td>
        <td><%= link_to 'Show', restaurant %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

food_delivery/app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>


<p>
<% if @restaurant.picture.attached? %>
<%= image_tag @restaurant.picture, size: 100 %>
<% end %>        
</p>
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>
<p> Блюда </p>
<div class="flex-parent">

<% @restaurant.dishes.each do |dish| %>
    <%= image_tag dish.picture, size: 100 %> 
    <%= dish.name %> </br>
    <%= dish.description %></br>
    <%= dish.price %> </br>
    <%= button_to "Add to cart", line_items_path(dish.id) %>
    
  <%end%>
</div>

<%= link_to 'Back', restaurants_path %>